import type { Metadata } from "next";
import React from "react";
import "@/assets/styles/globals.css";
import HeaderComponent from "@/components/layouts/HeaderComponent";
import FooterComponent from "@/components/layouts/FooterComponent";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { NotiProvider } from "@/components/notifications/CustomNoti";
import { AsideNav } from "@/components/layouts/aside/AsideNavComponent";

export const metadata: Metadata = {
  title: "Vietnix Store - VIETNIX.VN",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{
  children: React.ReactNode;
}> = React.memo(function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-gray-50">
        <NotiProvider />
        <LanguageProvider>
          <div className="flex flex-col min-h-screen">
            <HeaderComponent />
            <div className="flex flex-1 lg:min-h-0">
              <div className="hidden lg:block">
                <AsideNav />
              </div>
              <main className="flex-1 p-2 sm:p-8">
                <div className="max-w-7xl mx-auto">
                  {children}
                </div>
              </main>
            </div>
            <FooterComponent />
          </div>
        </LanguageProvider>
      </body>
    </html>
  );
});

export default RootLayout;
