import type { Metadata } from "next";
import "../assets/styles/globals.css";
import HeaderComponent from "../components/Layouts/Header";
import FooterComponent from "../components/Layouts/Footer";
import { LanguageProvider } from "@/context/LanguageContext";

export const metadata: Metadata = {
  title: "Vietnix Store - VIETNIX.VN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <LanguageProvider>
          <HeaderComponent />
          {children}
          <FooterComponent />
        </LanguageProvider>
      </body>
    </html>
  );
}
