import type { Metadata } from "next";
import "@/assets/styles/globals.css";
import HeaderComponent from "@/components/layouts/HeaderComponent";
import FooterComponent from "@/components/layouts/FooterComponent";
import { LanguageProvider } from "@/context/LanguageContext";
import { NotiProvider } from "@/components/notifications/CustomNoti";
import { AsideNav } from "@/components/layouts/aside/AsideNavComponent";

export const metadata: Metadata = {
  title: "Vietnix Store - VIETNIX.VN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <NotiProvider />
        <LanguageProvider>
          <div className="flex flex-col flex-1 min-h-screen">
            <HeaderComponent />
            <div className="flex flex-1">
              <div className="flex-1 bg-gray-50">
                <div className="flex flex-row h-full w-full">
                  <div className="hidden lg:block">
                    <AsideNav />
                  </div>
                  <main className="h-full w-full p-2 sm:p-8 sm:mx-auto">
                    {children}
                  </main>
                </div>
              </div>
            </div>
            <FooterComponent />
          </div>
        </LanguageProvider>
      </body>
    </html>

  );
}
